#!/bin/sh

# Install packages
wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | apt-key add -
echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list
apt-get update -y
apt-get install -y php jenkins
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
composer install

# Set swap memory
free -m
dd if=/dev/zero of=/swap bs=1M count=1024
mkswap /swap
swapon /swap
free -m

# Switch user
su - jenkins
