#!/bin/sh

# Create ssh keys
ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''

# Save ssh keys to digital ocean?
php /home/jenkins/setup.php

# Output the Jenkins admin password
cat /var/lib/jenkins/secrets/initialAdminPassword
